# Site settings
name: Mo0O
title: Mo0O's notes
email: mo0ofier@gmail.com
description: "Mo0O's notes, the place where I put thinks and works I want to share."
baseurl: ""
url: "https://github.com/WnP"
twitter_name: 5733v3
github_name: WnP

# Build settings
markdown: kramdown
permalinks: pretty

# Analytics
analytics:
    provider: google
    google:
        tracking_id: 'UA-61296913-1'
